const productos = [
	{
		id: "1",
		nombre: "Adacel",
		laboratorio: "Sanofi-Pasteur",
		imagen: "../imagenes/ADACEL (2).jpg",
		descripcion: "Vacuna de toxoides tetánico y diftérico",
	},
	{
		id: "2",
		nombre: "Menactra",
		laboratorio:"Sanofi-Pasteur",
		imagen: "../imagenes/MENACTRA.jpg",
	
		descripcion: "Vacuna Antimeningocóccica contra subgrupos A,C y W-135",
	},
	{
		id: "3",
		nombre: "Moto G42",
		marca: "Motorola",
		imagen: "../images/moto-G42.webp",
		precio: 75,
		descripcion: "Smartphone Android. Potenciado por un procesador MediaTek Helio",
	},
	{
		id: "4",
		nombre: "Galaxy A34",
		marca: "Samsung",
		imagen: "../images/samsung-galaxy-a34.jpg",
		precio: 80,
		descripcion: "Es el sucesor del Galaxy A33 5G. Con una pantalla Super AMOLED de 6.6 pulgadas",
	},
	{
		id: "5",
		nombre: "Galaxy M54",
		marca: "Samsung",
		imagen: "../images/samsung-galaxy-m54.jpg",
		precio: 80,
		descripcion: "Se suma a la serie Galaxy M con una pantalla Super AMOLED",
	},
	{
		id: "6",
		nombre: "Galaxy S10e",
		marca: "Samsung",
		imagen: "../images/samsung-galaxy-S10e.webp",
		precio: 85,
		descripcion: "Pantalla Full HD",
	},
	{
		id: "7",
		nombre: "Galaxy Tab S6 Lite",
		marca: "Samsung",
		imagen: "../images/samsung-galaxy-tab-S6-Lite.webp",
		precio: 90,
		descripcion: "Pantalla Full HD",
	},
	{
		id: "8",
		nombre: "30 SE",
		marca: "TCL",
		imagen: "../images/TCL-30-SE.webp",
		precio: 95,
		descripcion: "Buen celular",
	},
];
